/**
 * Augments the generated Cloudflare `Env` interface with the secrets +
 * vars we declare in `wrangler.jsonc`. Keeps the generated
 * `worker-configuration.d.ts` untouched (it gets regenerated by
 * `wrangler types`), while still giving us typed `env.CPAY_*` access.
 */
interface Env {
  CPAY_API_KEY: string;
  CPAY_SECRET: string;
  CPAY_INTEGRATION: string;
  CPAY_ENVIRONMENT?: ConvesioPayEnvironmentValue;
  /** Optional. When set, a successful payment POSTs an `order.created` event
   *  to this Store Manager campaign webhook. Unset → notification is skipped. */
  STORE_MANAGER_CAMPAIGN_URL?: string;
}

type ConvesioPayEnvironmentValue = "test" | "live";
